blog/config/routes.rb
Rails.application.routes.draw do

  
  resources :categories
  resources :articles do
    resources :comments, only:[:create,:destroy,:update,:show]
  end
  devise_for :users
  root 'welcome#index'
  get '/dashboard' , to: "welcome#dashboard"

end

blog/app/models/article.rb
class Article < ActiveRecord::Base

	include AASM

	belongs_to :user
	has_many :comments
	validates :title,presence: true, uniqueness: true
	validates :body,presence: true, length: { minimum: 20}
	before_save :set_visits_count
	after_create :save_categories
	after_create :send_mail

	 has_attached_file :cover, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
 	 validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
	def categories=(value)
		@categories=value
	end
	def update_visits_count
		self.update(visits_count: self.visits_count + 1)
	end

	private
	def send_mail
		ArticleMailer.new_article(self).deliver_later
	end

	def save_categories
		unless @categories.nil?
		@categories.each do |category_id|
			HasCategory.create(category_id: category_id,article_id: self.id)
		end
		end
		
	end
	def set_visits_count
		self.visits_count ||= 0
	end
end

blog/app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, presence: true
	has_many :has_categories
	has_many :articles, through: :has_categories
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

blog/app/models/has_category.rb
class HasCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

blog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :comments
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_categories

  private
  def set_categories
  	@categories=Category.all
  end
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user! ,except: [:index]
	before_action :set_article, except: [:index,:new,:create]
	def index
		@articles=Article.paginate(page: params[:page],per_page:4).all
	end
	def show
		@article.update_visits_count
		@comment=Comment.new
	end
	def new
	 	@article=Article.new
	 	@categories=Category.all
	end
	def edit
	end
	def update
		if @article.update(article_params)
			redirect_to @article
		else
			render :edit
			
		end
	end
	def create
		@article =current_user.articles.new(article_params)
		@article.categories =params[:categories]
		if @article.save
		redirect_to @article
		else
		render :new
	    end
	end
	def destroy
		@article.destroy
		redirect_to articles_path
	end
	def validate_user
		redirect_to new_user_session_path, notice: "Necesitas Iniciar Sesión"

	end
	def set_article
		@article=Article.find(params[:id])
	end

	private
	def article_params
		params.require(:article).permit(:title,:body,:cover,:categories,:markup_body)
	end
end

blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :color)
    end
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :destroy,:show]
  before_action :set_article
  before_action :authenticate_user!

def show
  
end
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @article
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment.article }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_article
    @article=Article.find(params[:article_id])
    
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def dashboard
  	
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/categories_helper.rb
module CategoriesHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/_form.html.erb
<%= form_for(@article, html:{ id:"articles_form"}) do |f| %>
<div>
<% @article.errors.full_messages.each do |m|%>
<div>
	<h3 class="rojo"><%= m %></h3>
</div>
<%end%>
	<%= f.text_field :title, placeholder: "Titulo"%>
	<br>
	<br>
</div>
<div class="body">
	<%= f.hidden_field :body, id:"body_textarea"%>
	<%= f.hidden_field :markup_body, id:"markup-body_textarea"%>
	<div id="epiceditor"></div>
</div>
<div>
	<label>Categorías</label>
	<div>
	<% @categories.each do |cat|%>
	<%= check_box_tag "categories[]",cat.id%>
	<%=cat.name%>
	<% end %>
	</div>
</div>
<br>
<div>
	<%= f.submit "Guardar", class:"btn-lg btn-primary"%>
</div>
<br>
<% end %>
<script>
	var editor = new EpicEditor({
		textarea: "markup-body_textarea",
		file:{
			name:"nuevo_articulo"
		}
	});
	editor.load();

	$("#articles_form").on("submit",function  (argument) {
		$("#body_textarea").val(editor.exportFile("nuevo_articulo","html"));
		$("#markup-body_textarea").val(editor.exportFile("nuevo_articulo","html"));
	});
</script>

blog/app/views/articles/edit.html.erb
<div id="formu">
<h1>Editar Articulo</h1>
<%= render "form"%>
</div>

blog/app/views/articles/index.html.erb
<% @articles.each do |a| %>
<h1><%= link_to a.title,a %>
</h1>
<div> <%= truncate(a.body,lenght:10) %>-><%= link_to  "Eliminar", a, method: :delete %>
</div>
<% end %>
<%= will_paginate @articles %>

blog/app/views/articles/new.html.erb
<div id="formu">
<h1>Crear Articulo</h1>
<%= render "form"%>
</div>

blog/app/views/articles/show.html.erb
<div>
  <div class="center">
<h1><%= @article.title %>
<% unless @article.user.nil?%>
	<h4>
Escrito por <%= current_user.email%>
</h4>
<%end %>
	<h4>
	Visitas :<%= @article.visits_count%>
</h4>
</h1>
<div> <%= Sanitize.fragment(@article.body, Sanitize::Config::RELAXED).html_safe %>
</div>
<div>
	<h3>Comentarios</h3>
	<%= render "comments/form"%>
</div>
	<div>
	<ul id="comments-box">
	<% @article.comments.each do |c| %>
	<li><%= c.body%> -<%= c.user.email%></li>
	<%end%>
	</ul>
	</div>
<div>
	<%= link_to "Editar", edit_article_path(@article)%>
</div>
</div>
</div>

blog/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.color_field :color %>
  </div>
  <div class="actions">
  <br>
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

blog/app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

blog/app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.color %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

blog/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

blog/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <h1 style="color:<%= @category.color;%>"><%= @category.name %></h1>
</p>
<% @category.articles.each  do |a| %>
<h1><%= link_to a.title,a %>
</h1>
<div> <%= a.body %>-><%= link_to  "Eliminar", a, method: :delete %>
</div>
<% end %>
<p>
  <strong>Color:</strong>
  <%= @category.color %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

blog/app/views/comments/_form.html.erb
<%= form_for([@article,@comment], remote: true, html: { id: "comments-form", :"data-type" => "json"}) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Comenta %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit "Crear Comentario", class:"btn btn-primary" %>
  </div>
<% end %>

blog/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

blog/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

blog/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link href='https://fonts.googleapis.com/css?family=Montserrat+Alternates' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "partials/navigation" %>

 <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

blog/app/views/partials/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Blog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Articulos' , articles_path %></li>
        <% @categories.each do |c| %>
        <li><%= link_to c.name , c %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in?%>
        <li><%= link_to "Nuevo Articulo", new_article_path %></li>
        <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete%></li>
        <%else%>
        <li><%= link_to "Iniciar Sesión", new_user_session_path %></li>
        <li><%= link_to "Crear Cuenta", new_user_registration_path %></li>
        <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

blog/app/views/welcome/index.html.erb
<% if user_signed_in?%>
<h1>Bienvenido <%= current_user.email%></h1>
<% end %>